export const LOGIN_IN = 'login_in'
export const UPDATE_INFO = 'updata_info'
export const AUTO_UPDATE = 'auto_play'
export const REQ_USER_LIST = 'req_user_list'
export const REQ_BOSS_LIST = 'req_boss-list'
export const LOG_OUT = 'log_out'
export const ADD_CHAT_TEXT = 'add_chat_text'
export const GET_CHAT_LIST = 'get_chat_list'
// export const GET_UN_READ = 'get_un_read'
export const ADD_UN_READ = 'add_un_read'

export const OFF_LINE_MSG = 'off_line_msg'